# Generated by Django 3.1.2 on 2021-01-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UDAdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartment',
            new_name='Blocks',
        ),
        migrations.RenameField(
            model_name='blocks',
            old_name='ap_Id',
            new_name='block_No',
        ),
        migrations.RenameField(
            model_name='blocks',
            old_name='ap_name',
            new_name='block_name',
        ),
    ]
