# Generated by Django 3.1.2 on 2021-01-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UDAdminApp', '0002_auto_20210127_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('flat_No', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('vacancy', models.CharField(choices=[('vacant', 'vacant'), ('avail', 'avail')], max_length=20, null=True)),
                ('size', models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK')], max_length=20, null=True)),
                ('floor', models.IntegerField()),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UDAdminApp.blocks')),
            ],
        ),
    ]
