# Generated by Django 3.1.2 on 2021-01-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UDAdminApp', '0003_flats'),
    ]

    operations = [
        migrations.AddField(
            model_name='flats',
            name='price',
            field=models.CharField(max_length=100000000, null=True),
        ),
    ]
