# Generated by Django 3.1.2 on 2021-01-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UDAdminApp', '0006_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
